# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae4f543c7b09e1c579b30d7a887a9dcca1c3265afa530e1e2ac1eb25033afb892112a88a6abe5ad6dca3d9c5695282332373424dfcdeafadb15fe425a474510f

test:
  secret_key_base: 8eaa06b9249e0be913e0b0d7049f658408b1fc292b40ac739ad645237ed28957241588396039639a818f4bc32edf817614682f071e48fbda1c67a0f0eeda2366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
